### ISSUE TITLE
Support JMS 2.0 and Jakarta Messaging 3.0 API

### ISSUE THREAD

**Issue by acogoluegnes** [rabbitmq/rabbitmq-jms-client#180]
# Background

RabbitMQ JMS Client 2.x supports JMS 1.1 API, it requires Java 8. This is the current version of the library.

JMS 2.0 introduces [API changes](https://www.oracle.com/technical-resources/articles/java/jms20.html) and some [new features](https://www.oracle.com/technical-resources/articles/java/jms2messaging.html). A JMS 2.0 client library must implement these changes. From an application developer's point of view, upgrading from JMS 1.1 to JMS 2.0 is transparent, minus some minor changes in the semantics of some methods. JMS 2.0 requires Java 8.

In 2018, as part of the Java EE to Jakarta EE migration, JMS became Jakarta Messaging, and [Jakarta Messaging 3.0](https://jakarta.ee/specifications/messaging/3.0/) was released. It requires Java 11. The name of the Java packages changed, so JMS 2.0 and Jakarta Messaging 3.0 are not compatible. Jakarta Message 3.0 does not bring any [other changes](https://jakarta.ee/specifications/messaging/3.1/jakarta-messaging-spec-3.1.html#version-3-0) though, so moving from JMS 2.0 to Jakarta Messaging 3.0 does not require much effort _for a JMS client library_.

Note: [Jakarta Messaging 3.1](https://jakarta.ee/specifications/messaging/3.1/) is available, with [minor tweaks](https://jakarta.ee/specifications/messaging/3.1/jakarta-messaging-spec-3.1.html#version-3-1).

[Spring 6.0](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x) (not released yet) will support Jakarta EE, and so Jakarta Messaging.

# Impact

The RabbitMQ JMS Client Library is a proven solution to migrate legacy systems to RabbitMQ with minor changes to existing JMS applications. The library can be used on its own or with [Spring JMS support](https://docs.spring.io/spring-framework/docs/current/reference/html/integration.html#jms).

The implementation of JMS 2.0 does not seem to be essential to users, as it's been requested only once in the last 6 years IIRC. The new features may not be critical and Spring JMS is a good substitute for the API improvements.

Staying compatible with Spring does matter: questions and issues from the community channels reference Spring often. It seems appropriate to keep up with Spring 6.0 by supporting Jakarta Messaging 3.0.

# Possible Roadmap

It's not realistic to go only with Jakarta Messaging, so we'll have to maintain 2 branches:
 - 2.x: JMS 1.1 or JMS 2.0, Java 8 or more.
 - 3.x: Jakarta Messaging 3.0, Java 11 or more.

It may be technically possible to support JMS 2.0 in 2.x, but this should also let the choice to use JMS 1.1.

A possible implementation path would be to support JMS 2.0 in 2.x and supporting Jakarta Messaging 3.0 in 3.x would be just a matter of renaming packages.

# Resources

JMS 1.1 to JMS 2.0:
 - https://www.oracle.com/technical-resources/articles/java/jms20.html
 - https://www.oracle.com/technical-resources/articles/java/jms2messaging.html

[JMS 2.0 specification (rev. a)](https://github.com/rabbitmq/rabbitmq-jms-client/files/9157328/JMS20.pdf), section "1.2. What is new in JMS 2.0?" for an overview and "A.1. Version 2.0" for details.

[Jakarta Messaging TCK](https://download.eclipse.org/jakartaee/messaging/3.1/jakarta-messaging-tck-3.1.0.zip)

[JMS 1.1 specification](https://download.oracle.com/otndocs/jcp/7195-jms-1.1-fr-spec-oth-JSpec/)

# Tasks

- [x] [New methods to create a session (JMS_SPEC-45)](https://jakarta.ee/specifications/messaging/3.1/jakarta-messaging-spec-3.1.html#new-methods-to-create-a-session-jms_spec-45) #200
- [x] [New createDurableConsumer methods (JMS_SPEC-51)](https://jakarta.ee/specifications/messaging/3.1/jakarta-messaging-spec-3.1.html#new-createdurableconsumer-methods-jms_spec-51) #201
- [x] [Multiple consumers now allowed on the same topic subscription (JMS_SPEC-40)](https://jakarta.ee/specifications/messaging/3.1/jakarta-messaging-spec-3.1.html#multiple-consumers-now-allowed-on-the-same-topic-subscription-jms_spec-40) #208
- [x] [Client ID optional on shared durable subscriptions (JMS_SPEC-39)](https://jakarta.ee/specifications/messaging/3.1/jakarta-messaging-spec-3.1.html#client-id-optional-on-shared-durable-subscriptions-jms_spec-39) (n/a, as the client ID is not taken into account for the subscription names currently)
- [x] [Delivery delay (JMS_SPEC-44)](https://jakarta.ee/specifications/messaging/3.1/jakarta-messaging-spec-3.1.html#delivery-delay-jms_spec-44) #222
- [x] [Sending messages asynchronously (JMS_SPEC-43)](https://jakarta.ee/specifications/messaging/3.1/jakarta-messaging-spec-3.1.html#sending-messages-asynchronously-jms_spec-43) #205 #206
- [x] [Use of AutoCloseable (JMS_SPEC-53)](https://jakarta.ee/specifications/messaging/3.1/jakarta-messaging-spec-3.1.html#use-of-autocloseable-jms_spec-53) (already implemented)
- [x] [JMSXDeliveryCount (JMS_SPEC-42)](https://jakarta.ee/specifications/messaging/3.1/jakarta-messaging-spec-3.1.html#jmsxdeliverycount-jms_spec-42) #202 (fully implemented with quorum queues, best effort for other queue types, see issue for details)
- [x] [Simplified API (JMS_SPEC-64)](https://jakarta.ee/specifications/messaging/3.1/jakarta-messaging-spec-3.1.html#simplified-api-jms_spec-64) #210
- [x] [Subscription name characters and length](https://jakarta.ee/specifications/messaging/3.1/jakarta-messaging-spec-3.1.html#subscription-name-characters-and-length-2) #203 (opt-in, disabled in 2.x, will be enabled by default in 3.0)
- [x] [New method to extract the body directly from a Message (JMS_SPEC-101)](https://jakarta.ee/specifications/messaging/3.1/jakarta-messaging-spec-3.1.html#new-method-to-extract-the-body-directly-from-a-message-jms_spec-101) #199
